### ISSUE TITLE
Implementing on Contact forms embedded on Product Pages?

### ISSUE THREAD

**Issue by virtual** [magento-hackathon/HoneySpam#10]
Hi all, this looks like a great plugin. I am trying to get it to load on a product page which uses tabs for a contact form. (Reference the Q&A tab near the middle of http://optechusa.com/straps/utility-strap-sling.html) 

On my local environment I was able to get the JavaScript include to load by adding the following before the closing </layout> tag:

``` xml
<!--app/design/frontend/base/default/layout/honeyspam.xml-->
<catalog_product_view>
    <update handle="honeypot"/>
    <reference name="contactForm">
        <block type="core/text_list" name="contacts.form.fields.before" as="form_fields_before" translate="label">
            <block type="hackathon_honeyspam/honeypot" name="honeyspam.honeypot"
                   template="hackathon/honeyspam/honeypot.phtml"/>
        </block>
    </reference>
</catalog_product_view>
``` 

However the honeypot input isn't showing up. I've tried to do a bit of research on block type and the name, but still can't figure it out. Could anyone point me in a direction that might help in implementing this? Thank you!

**Comment by michaelscheel** [comment]
Sehr geehrte Damen und Herren,

ich befinden mich bis zum 05.09.2016 nicht im Büro. In dringenden Fälle wenden Sie sich bitte an meinen Kollegen Tobias Völker voelker@virtualways.de.

Mit freundlichen Grüßen 

Michael Scheel

**Comment by Schrank** [comment]
Hi virtual, great you like our extension!

**You should never change any core files, this includes any files coming with an extension!**

The alternative is to implement your own module or use your theme's [local.xml](http://magebase.com/magento-tutorials/5-useful-tricks-for-your-magento-local-xml/)

- [Did you add the form_fields_before to your contact form?](https://github.com/magento-hackathon/HoneySpam#contacts-form-modifications)
- Is your form which you include on the product detail page its own block and named `contactForm`?

**Comment by virtual** [comment]
Thank you for your help @Schrank! I really appreciate it. 

I've included my setup; I hope this is a fix of not understanding the right reference name and block names to use within the local.xml. The JavaScript is being included in the head.
 

I've moved this to our local.xml:
app/design/frontend/smartwave/optechusa/layout/**local.xml**
``` xml
<catalog_product_view>
    <update handle="honeypot"/>
    <reference name="contacts_tabbed_contents">
        <block type="core/text_list" name="contacts.form.fields.before" as="form_fields_before" translate="label">
            <block type="hackathon_honeyspam/honeypot" name="honeyspam.honeypot"
                   template="hackathon/honeyspam/honeypot.phtml"/>
        </block>
    </reference>
...
```

I can test and tell that it is being called from
app/design/frontend/smartwave/optechusa/template/catalog/product/**view.phtml**
``` php
...
<div id="contacts_tabbed_contents" class="tab-content" style="display: none;">
    <div><h2>Questions &amp; Answers</h2></div>
    <div class="std">
    <?php if ((!is_null($_product->getData('questions')))) { ?>
        <?php echo $_product->getData('questions'); ?>
        <hr>
    <?php } ?>
    I'm called
    <?php echo $this->getChildHtml('contactForm'); ?>
    </div>                
</div>
....
```

I do have the form_fields_before added to 
app/design/frontend/smartwave/optechusa/template/contacts/**form.phtml:**

 

``` php
...
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<form action="/contacts/index/post/" id="contactForm" method="post">
   Get here
    <?php echo $this->getChildHtml('form.fields.before'); ?>
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Ask OP/TECH USA a Question') ?></h2><br />
```

The resulting output is: (http://magentotest.local/soft-pouch-digital-d-series.html)
``` html
...
<hr>
I'm called
<div id="messages_product_view"></div>

<form action="/contacts/index/post/" id="contactForm" method="post">
Get here
<div class="fieldset">
<h2 class="legend">Ask OP/TECH USA a Question</h2><br>
...
```

**Comment by Schrank** [comment]
I'm not sure whether I don't get the whole context or you don't understand magentos layout.xml so please don't be offended, if I start to early.

I assume `app/design/frontend/smartwave/optechusa/template/catalog/product/view.phtml` is the block `contacts_tabbed_contents`.

Then you have inside a block:

    <block type="core/text_list" name="contacts.form.fields.before" as="form_fields_before" translate="label">

so inside of your template you can access this block either via name or alias (as):

    name="contacts.form.fields.before"
    as="form_fields_before"

So your code should be `<?php echo $this->getChildHtml('form_fields_before'); ?>` instead of `<?php echo $this->getChildHtml('contactForm'); ?>`

The alternative is, if `app/design/frontend/smartwave/optechusa/template/contacts/form.phtml` is your block `contacts_tabbed_contents`, then still you need to change `<?php echo $this->getChildHtml('form.fields.before'); ?>` to `<?php echo $this->getChildHtml('form_fields_before'); ?>`


If this is your problem, I can recommend Alan Storms book :-) http://store.pulsestorm.net/products/no-frills-magento-layout

Good luck!

**Comment by virtual** [comment]
Hi @Schrank! Thank you for pointing me in the right direction. I purchased Alan's book and found the partial code I needed in layout.xml to be the following:
``` xml
<catalog_product_view>
      <update handle="honeypot"/>
      <reference name="product.info">
          <block type="core/template" name="contactForm" template="contacts/form.phtml">
              <block type="core/text_list" name="contacts.form.fields.before" 
              as="form_fields_before" translate="label">
                  <block type="hackathon_honeyspam/honeypot" 
                         name="honeyspam.honeypot"
                         template="hackathon/honeyspam/honeypot.phtml"/>
              </block> 
          </block>
      </reference>
</catalog_product_view>
```

**Comment by Schrank** [comment]
Great to hear you got it! <3
