### ISSUE TITLE
Honeypot for Newsletter-Subscription

### ISSUE THREAD

**Issue by Elfen-Service** [magento-hackathon/HoneySpam#14]
Hello,

we use this extension with success for years now.
But would be good to have it in the form for Newsletter-Subcription (e.g. in thee footer).
Yesterday we had a bot putting in hundreds of addresses in the form, again.

**Comment by Schrank** [comment]
Good point, thanks!

Beside this, there are a couple of reasons you don't want to use Magento for newsletters:
- If your server ends up on a blacklist, your order, invoice, etc. emails don't reach your customers too.
- It doesn't log automatically who registered when
- doesn't take care of unsubscribe links, ...

**Comment by Elfen-Service** [comment]
We use it only for collecting the addresses and and give the users the possibility to unsubscribe. :)

**Comment by inpresif** [comment]
I had the same question/request. We've been hit by (the same?;-)) bot as well yesterday. Trying to figure out how to update the newsletter handle to include the code but having no luck.

The latest being this but that does not work either:
    <newsletter_manage_index>
        <update handle="honeypot"/>
        <reference name="customer_newsletter">
            <block type="hackathon_honeyspam/honeypot" name="honeyspam.honeypot"
                   template="hackathon/honeyspam/honeypot.phtml"/>
        </reference>
    </newsletter_manage_index>

Please add it, it would be very helpful.

Thanks.

ps. Like Elfen-Service, we also only use the newsletter form to collect and then sync with mailchimp. However, hotmail already listed us as spam, which we will now have to go and undo again.

**Comment by inpresif** [comment]
It seems to work fine, I un-hide the form, filled it in and the error message appeared. All seems good.

**Comment by sprankhub** [comment]
This has now been implemented in the master branch.
