### ISSUE TITLE
Multiple Spam Protections On One Page

### ISSUE THREAD

**Issue by sprankhub** [magento-hackathon/HoneySpam#19]
Currently, the honeypot is hidden via `$('url').hide();`. The issue is that the honeypot has an ID, which has to be unique by definition. Currently, if there are two honepots on one page (e.g. one newsletter registration form in the footer and the normal `customer/account/create` form), the second honeypot field is not hidden, because it is not catched by the expression `$('url')`. I would suggest deleting the ID of the honeypot form field and add a class `mhhs-url` (Magento Hackathon Honey Spam URL) :D Then we should update the JS (after #18 has been merged) to `$$('.mhhs-url').each(Element.hide);` and we should be good.

What do you think? I am happy to provide a PR if you like the idea.

**Comment by Schrank** [comment]
The id is part of the honeypot. So I think we better have a bunch of fields a bot wants to fill and give each field another id. All the same class and perfect.

Url, credit card number, ss number, car type!

Something like this

**Comment by sprankhub** [comment]
So the ID is important and without an ID, the bots would not fill the field? Sounds weird to me, but bots are weird anyway.

Then we would need a different input field for each and every form, in which we include a honeypot.

**Comment by Schrank** [comment]
Not exactly. I thin when the field has an id url the probability to get filled is higher.

**Comment by tobiasdalhof** [comment]
This can be closed I guess? See PR #20

**Comment by Schrank** [comment]
Unfortuantely not, we need to find a solution for the currently hardcoded url. I prefer to not just remove it, because the bots should have one more reason to fill the field

**Comment by tobiasdalhof** [comment]
Why don't we just say input element id = HoneypotName?

**Comment by Schrank** [comment]
Because I didn't spend a second yet, thinking about that. Good idea - would you mind doing that? :-)

THEN we can close this 👍

**Comment by Schrank** [comment]
argh. no the name comes from config. We need to set the name on the block. Maybe we just remove the config stuff, set it hard in the layout.xml and if anyone wants to set another name, just change the layout. Or for a second block, add the layout and name...

**Comment by kortwotze** [comment]
We could make a list of IDs that bots really like and have each honeypot field use one of them at random. Then maybe even use a data-attribute to catch them with jQuery and do a .each() loop to hide n fields on a page.

I am thinking of trying to work on this project again. :D
