### ISSUE TITLE
Hidden input field to other forms too?

### ISSUE THREAD

**Issue by xkouhiax** [magento-hackathon/HoneySpam#2]
Is it possible to add input field to other forms too? I have couple of contact and request contact -forms in the Magento eshop and spam is problem on those. HoneySpam Readme says only that input field is added in the Customer Register and in the Product Review Form. How to add it to my custom forms?

**Comment by Schrank** [comment]
Hi @xkouhiax sorry for the very, very late answer. Yes this is possible. Have a look into `\Hackathon_HoneySpam_Model_Observer` how to check what was submitted and into `app/design/frontend/base/default/layout/honeyspam.xml` how to add the honeypot field.
