### ISSUE TITLE
Error : 100 router match iterations

### ISSUE THREAD

**Issue by prashantatlasinfotech** [magento-hackathon/HoneySpam#21]
Hi,

I install extension on my site. It does not worked for me. After submitting the registration form i got the error of "100 router match iterations". I debug the issue and issue is generated for following link of extension code. 

Following code generate issue and file is observer.php 

$e = new Mage_Core_Controller_Varien_Exception();
$e->prepareForward('index','error','honeyspam');

If have any idea why this issue generated. kindly guide. Thanks in advanced.

**Comment by Schrank** [comment]
Thanks for the report.

Did you flush the cache? I didn't had this error ever.

Do you know which of these is causing this error?
https://github.com/magento-hackathon/HoneySpam/blob/master/app/code/community/Hackathon/HoneySpam/Model/Observer.php#L33-L43

**Comment by prashantatlasinfotech** [comment]
Hello Schrank,

Thanks for your reply. 

I tried with Clean and flush the cache. I am using redis cache. I also flush the redis cache. But issue is still there. May be some other extension conflict with this extension.

https://github.com/magento-hackathon/HoneySpam/blob/master/app/code/community/Hackathon/HoneySpam/Model/Observer.php#L33-L35

It gives error on  $this->_checkHoneypot(); line. But actually it gives error for following line.

$e = new Mage_Core_Controller_Varien_Exception();
$e->prepareForward('index','error','honeyspam');

This code is call in all three function _checkHoneypot(), _checkTimestamp() and _indexLoginParams(). So may be it will not work for all three functions.


Thanks,
Prashant

**Comment by sprankhub** [comment]
I cannot reproduce this. For me, when this issue occured, it could always be solved by flushing the cache. See https://github.com/convenient/magento-ce-ee-config-corruption-bug for more details.

I also checked the history of `Mage_Core_Controller_Varien_Exception::prepareForward`, but it already looked the same in Magento 1.4. Which version of Magento do you use?

**Comment by prashantatlasinfotech** [comment]
Hello Schrank,

I am using megento community edition version is 1.9.0.1.  I think other extension conflict with this extension and due to this error occur.  When i directly access the url 'honeyspam/error/index'  it shows the message "The form could not be sent because of SPAM detection!". But when customer register at that time it gives error. 

I also refer the link https://github.com/convenient/magento-ce-ee-config-corruption-bug. If i apply this solution then honeyspan extension validation does not fire. 

Thanks,
Prashant

**Comment by Schrank** [comment]
If another extension is causing this error, you have a problem, we can't fix. xdebug might help you find the problem.

If you want paid support, tell us.
