### ISSUE TITLE
Does not seem to be working

### ISSUE THREAD

**Issue by plumbingdeals** [magento-hackathon/HoneySpam#25]
Have a Magento CE1.9.2.4 e-commerce website.
Have installed the program and made edits for newsletter signup, however false signups continue.
Any suggestions?
Thank you.

**Comment by sprankhub** [comment]
Do you see the additional form field in the HTML code of the signup form? (Just to make sure that the extension is installed properly)

If the additional form field is present, try to rename the field in the system configuration to "email2". In my experience, this works much better than our default name "url".

**Comment by plumbingdeals** [comment]
Not sure what you mean, I still learning....

What should I see in the HTML code?

Thank you,

**Comment by sprankhub** [comment]
You should see the honeypot field in the HTML. Simply search for e.g. `mhhs-input`.

**Comment by plumbingdeals** [comment]
Yes, I found it, code is there in HTML...however it still does not 
appear to be working. I made the change to email2, that didn't help.

Any other suggestions...?

Thanks for the help, I do appreciate it.

**Comment by sprankhub** [comment]
To be sure that the code works in general: Remove the `display: hidden` from the honeypot field via the developer toolbar, fill the field and submit the form. If the submission is blocked, we know that the code works in general. Then the bot, which bugs you is simply too smart for this approach. You can still try to also change the type of the input field to `email`, maybe this works better. And if this still does not solve it, you should probably go with some form of CAPTCHA.

**Comment by plumbingdeals** [comment]
I think I got it...

Is this what should happen if everything is working right....

If so, changing input field to "email" was the trick.

Thank you so much for your help!

**Comment by sprankhub** [comment]
You should be redirected to a page, which says something like "Spam detected".

Glad that it helped!
