### ISSUE TITLE
Hidden input doesn't appear

### ISSUE THREAD

**Issue by digitupgr** [magento-hackathon/HoneySpam#28]
Hi

Thanks for the great work, however after installation doesn't load the hidden input at front end. We have create a custom newsletter phtml form and we load it into static block with the following code 
{{block type="newsletter/subscribe" name="newsletter" template="newsletter/subscribe_footer.phtml"}} Also, we put your code into form without any result.

Do you have any idea what we should change to works properly?

Thanks

**Comment by Schrank** [comment]
Please check https://github.com/magento-hackathon/HoneySpam/issues/26

HTH
