### ISSUE TITLE
the form could not be sent because of SPAM detection

### ISSUE THREAD

**Issue by MalwinaDD** [magento-hackathon/HoneySpam#29]
Hello,
I use HoneySpam on website https://dentaldirect.co.uk/. When some customers try to open an account the error occurs. Error message “the form could not be sent because of SPAM detection”. It happens rarely and without any logic. Any suggestions what is the possible reason?

**Comment by Schrank** [comment]
The spam detection works via a hidden input field, which is filled by bots but not by humans. I could assume, that if you use a password manager like LastPass or 1Password, that they fill the field too, so the detection has a false positive.

You can try to rename the field in the backen.

**Comment by MalwinaDD** [comment]
Hi Fabian,

 

Thank you for your reply. Regarding the problem I’ve written you about, I consider to change the hidden filed from “url” to something completely random ie “egfe”

Do you think it might help? In case I’d like to make such change is it enough to edit honey spam settings in magento backend or do I have to edit code as well?

 

 

Kind regards,

Malwina Palinska

Malwina Palinska | Digital Marketing Manager | Dental Direct | Tel: +44 20 8438 1585 | Email:  <mailto:Malwina@dentaldirect.co.uk> Malwina@dentaldirect.co.uk
