### ISSUE TITLE
hidden field - URL

### ISSUE THREAD

**Issue by MalwinaDD** [magento-hackathon/HoneySpam#31]
I consider changing the hidden filed from “url” to something completely random ie “cxcytg”
This is regarding error message “the form could not be sent because of SPAM detection”, which seems to be caused by password managers and chrome autofill - tools which fill the form for you and the hidden field as well.

Do you think it might help? Has anybody tried it?  In case I’d like to make such change is it enough to edit honey spam settings in Magento backend or do I have to edit the code as well?

**Comment by tobiasdalhof** [comment]
I think bots are more unlikely to fill honeypots with random input names.

How about adding `autocomplete="false"` to the input?

**Comment by Schrank** [comment]
Sounds good! PR welcome

Von unterwegs gesendet

**Comment by tobiasdalhof** [comment]
Done

**Comment by Schrank** [comment]
Thanks! Currently on the train, will review later today

Von unterwegs gesendet
