### ISSUE TITLE
Input code doesn't appear

### ISSUE THREAD

**Issue by maxibel** [magento-hackathon/HoneySpam#36]
I have followed all steps, module is installed, .js is in the code, but <input id="url" isn't appearing within <form> tags. I have modified following files: 
/app/design/frontend/rwd/default/template/newsletter/subscribe.phtml
/app/design/frontend/rwd/default/template/contacts/form.phtml
Could you have some clue to find what is missing? Thank you!

**Comment by MahmoudDolah** [comment]
I have also noticed this behaviour
I theorize that this module doesn't work on community edition sites, only enterprise edition ones

Can a maintainer of this confirm?

**Comment by Schrank** [comment]
No, this extension is definitly working.
Where does it not work?

- Please make sure the extension is loaded (check for an entry in System > Configuration > Advanced)
- Make sure the layout.xml is loaded (break the xml and an error should be thrown)
- Make sure the extension is turned on in the backend "Enable hidden honeypot field"

Make sure the referenced blocks exist in your templates (https://github.com/magento-hackathon/HoneySpam/blob/master/app/design/frontend/base/default/layout/honeyspam.xml):

        <reference name="left.newsletter">
        <reference name="footer.newsletter">
        <reference name="newsletter">
        <reference name="form.additional.info">
        <reference name="form.additional.info">
        <reference name="product.review.form.fields.before">
        <reference name="contactForm">

**Comment by maxibel** [comment]
This module is working in contact form, but not in newsletter block in footer: http://bit.ly/2HHI873 .

**Comment by Schrank** [comment]
Please check the questions :-) It might be, that we are lacking RWD support.

**Comment by markoshust** [comment]
it's working great on rwd, i just paid a PR to update the readme for it's usage
