### ISSUE TITLE
Redirect to the actual page and show error as standard message

### ISSUE THREAD

**Issue by vishy93** [magento-hackathon/HoneySpam#40]
I am a big fan of this extension, however I have a slight issue. Whereby, when the HoneySpam field is filled it will redirect you to the page such as customer/account/createpost/ on the register page.

What I would like is for it to rather than redirect me there is it possible to keep them on the same page and just show the error as a normal magento error message?

**Comment by sprankhub** [comment]
You could implement this yourself (create a Honeyspam AJAX request first, wait for response, show message or submit form as usual if everything is okay), but this is nothing I would consider adding to the extension, sorry.

**Comment by vishy93** [comment]
@sprankhub Yes of course but going to the post url page to just show an error won't be good will it? 

For example, I know magento by default has the hideit field for contact us page, which in essence does the same thing as HoneySpam there but just throws and catches an error. Then redirects back and adds the error to session:


  ```
Mage::getSingleton('customer/session')->addError(Mage::helper('contacts')->__('Unable to submit your request. Please, try again later'));

$this->_redirect('*/*/');
```

**Comment by vishy93** [comment]
I agree whole heartedly for the bots. But, what about the situation of firstname equalling last name check? It would be a nice standard practices following thing to have error on the same page.

Also, it redirects you back to the actuall post URL, which although trivial I dont like.
