### ISSUE TITLE
Duplicate field error when you use in the Newsletter subscription

### ISSUE THREAD

**Issue by vishy93** [magento-hackathon/HoneySpam#41]
Using this in the Newsletter subscription will cause the error:

> [DOM] Found 2 elements with non-unique id #url error 

Therefore, wouldn't it be appropriate to remove the id declaration? 

It is not being used anywhere, and would help prevent his error!

**Comment by sprankhub** [comment]
This is indeed an issue. @Schrank said that it is more likely that the field is filled by bots if it has an attibute `id="url"`. Not sure if it would work without it. I guess most of the bots would fill it anyway. Could you remove it and give us feedback whether it still works @vishy93?

**Comment by vishy93** [comment]
@sprankhub Removing the id caused no issue and works fine for me. I shall do more testing, and see if I can look into the robot side. Will keep you posted.

**Comment by vishy93** [comment]
Looking into further I could find no evidence to suggest having an id in the field would cause greater filling in by bots.

**Comment by sprankhub** [comment]
Thanks for your feedback @vishy93! I would still love to hear something from @Schrank. If he thinks this is OK, I am fine with removing the `id` attribute.

**Comment by vishy93** [comment]
No worries @sprankhub :)

**Comment by Schrank** [comment]
LEt'S remove it.
