### ISSUE TITLE
input field url  no required?

### ISSUE THREAD

**Issue by marcelmastel** [magento-hackathon/HoneySpam#45]
Hi,
I installed honeyspam and i have input field "url" in contact form and signup, but I don't resolve spam.
But I think: input field hidden via js it's ok, but should be a required field. Right?

**Comment by sprankhub** [comment]
No, it should definitely not be required, because normal users cannot and should not fill the field.

Please see other similar issues if spam is not resolved with it. One of the ideas is to change the name of the input field. I often use "email2".

**Comment by Schrank** [comment]
I think the spam bots nowadays are not (as in the past) crawling the web, finding a form and fill it. But are specialized in Magento and fire directly to the controller and therefore this doesn't work anymore :-/
