### ISSUE TITLE
Remove / Comment Mage::log Calls

### ISSUE THREAD

**Issue by sprankhub** [magento-hackathon/HoneySpam#47]
I am pretty annoyed by all the `system.log` entries I get due to this extension. I would like to either remove or at least comment the `Mage::log` calls, so that the `system.log` is not filled with unimportant data. I am fine with implementing it and sending a pull request, but please give me your opinion first. Options:

1. Please keep the logging as it is.
2. Please completely remove the `Mage::log` calls.
3. Please keep the `Mage::log` calls, but add a line comment to it.

I vote for option 2.

/cc @Schrank

**Comment by Schrank** [comment]
I have no clue what is ligges, bit when you want to remove them, they seem to have no value.

Go for it.

**Comment by sprankhub** [comment]
Example log:

    Honeypot Input filled. Aborted.

This adds no value at all IMHO.

**Comment by Schrank** [comment]
Agrgee. Please remove it :)

**Comment by sreichel** [comment]
4. optionally write log to to own file.

@sprankhub i frequently check the kog for this, just to know whats going in in my shop :)

**Comment by Schrank** [comment]
Or make it optional with a system.xml entry? @sreichel you want to send a PR as you want it? @sprankhub

**Comment by sreichel** [comment]
Yes, I can send a PR.

Is it enough to make logging optional and change logfile name in code  (honeyspam.log?), to keep system.log clean?

**Comment by Schrank** [comment]
I'm happy with one of the two @sprankhub ?

**Comment by sprankhub** [comment]
I really do not know why one would need these entries, but anyway :-)

I suggest a simple logging yes/no configuration setting. Defaults to no. If set to yes, log is written to `honeyspam.log`.
