### ISSUE TITLE
3 Consonant rule

### ISSUE THREAD

**Issue by prophotorental** [magento-hackathon/HoneySpam#54]
Thank you for your efforts on this module. As others have said, HoneyPot modules are few for Magento, and yours seems to work very well so far.
I have one issue that I'm hoping you can help with. Looking through honeyspam.log, I see a LOT of legitimate entries that are being flagged as Spam because they have "3 or more consecutive consonants".  This is actually a fairly common occurrence in names (especially when "Y" is considered a consonant).  Is there some code I can change to increase that rule to 4 consonants and/or add "Y" as a vowel?
Thanks again for your help.  I understand this is a non-supported module, so I'd like to do as much of the work myself as possible (even though I am definitely not a software engineer).

**Comment by riconeitzel** [comment]
Hi!

https://github.com/magento-hackathon/HoneySpam/blob/1b5ba12ec5737f78fb1a746d5d28185bfa035920/app/code/community/Hackathon/HoneySpam/Model/Checker.php#L105

Here is the rule. Core hack would be okay for the beginning.

Change {3} to {4}

But y isn’t considered a vowel here!

Rico

**Comment by prophotorental** [comment]
Thank you for your help. I understand about "Y" being sometimes a vowel and sometimes not. The issue (at least in the US) is that many people shorten their name to have a Y on the end. E.g. Danny, Jenny, Lonny, Sammy, etc.  I don't want those legitimate registrations to be marked as Spam.
Now that I know the file to change, I can easily change it to fit our needs.  Thank you very much!
