### ISSUE TITLE
Field not appearing - problem with store codes in URL?

### ISSUE THREAD

**Issue by WPUtvecklare** [magento-hackathon/HoneySpam#61]
I can't get the hidden input field inside the contact form. I have made sure that the block name is `contactForm` and I'm including `echo $this->getChildHtml('form_fields_before');` right after the opening `form` tag. 

Could it possibly have something to do with the fact that I'm using store codes, which means that the form action URL becomes: website.com/en/contacts/index/post/. Just a thought, since I can't get it to work.

**Comment by sprankhub** [comment]
Are you totally sure that you edit the correct template? So if you add random text instead of the `getChildHtml` call, you see that random text in your store?

I cannot tell what the issue is, but it is **very** unlikely that the store codes are an issue.

**Comment by WPUtvecklare** [comment]
Yes, I can see other text as well, just gave it a try.

**Comment by sprankhub** [comment]
Are you sure the `HoneySpam` module is installed (and configured) correctly? Do you see the fields in other forms?

**Comment by WPUtvecklare** [comment]
I can't see the fields in other forms but yes, I am sure that it's installed correctly (I can see the editable fields in the Admin area).

**Comment by sprankhub** [comment]
Did you clear the cache? Maybe your theme changes the name of the contact form block? I think we cannot give any more help here without having access to your system :-/ Feel free to contact one of the [contributors](https://github.com/magento-hackathon/HoneySpam/graphs/contributors) for paid support.
