### ISSUE TITLE
Magento 2

### ISSUE THREAD

**Issue by Eddcapone** [magento-hackathon/HoneySpam#62]
Hello, do you plan to develop a solution for magento 2?
Or do you know a good alternative?

**Comment by sprankhub** [comment]
There are no immediate plans to implement that module for Magento 2.

Bots get smarter and smarter these days and my feeling is that honeypot solutions are in many cases not sufficient anymore. The latest version of Magento 2 comes with a Google reCAPTCHA integration, so I would consider switching to that.
