### ISSUE TITLE
Dont understand how to run the code

### ISSUE THREAD

**Issue by MatteoCalmes** [magento-hackathon/HoneySpam#63]
Hello guys, i don't know if it's the good place to ask my question (if it's not tell me). I got a problem im new on magento and didn't understand how to setup the code, i copy all the files in my magento application, but i don't understand when you say "Copy the file app/design/frontend/{base_or_rwd}/default/template/contacts/form.phtml to your own theme and insert the code"
 //<?php echo $this->getChildHtml('form_fields_before') ?>
"within the <form> ... </form> tag"
What i need to do ? i already just put the line of code in my template, but it's did't work. Do i need to copy the template under app/design/frontend/base/default/template/hackathon/honeyspam/ ?
I would be really grateful if you could help me

**Comment by MatteoCalmes** [comment]
I will give some details, i want to use the module in a custom contact form, for more understandability i try to add the field in this custom template app/design/frontend/alexandreturpault/default/template/contact/formParticuliers.phtml. i have already try to add the layout and template in the good way but the hidden field is still not here. 
Does the problem come from the fact that the file is called contact and not contactS ?

**Comment by sprankhub** [comment]
I am sorry, but I fear you need to hire a developer to do this for you. It is kind of impossible to support you remotely without having access to your code base :-(
