### ISSUE TITLE
Possible Issue

### ISSUE THREAD

**Issue by ADDISON74** [magento-hackathon/HoneySpam#65]
This is related to Newsletter subscription. How to simulate this issue:

1. In your browser inspect the code and find the input box with class named mhhs-input. Uncheck display: none and the input box will be visible in frontend.

2. Fill up both input boxes and click the button.

Now the URL is https://mydomain.tld/newsletter/subscriber/new/ and you will see the error message "The form could not be sent because of SPAM detection!".

In this page fill up the input box with an email address and press the button. The page is not loading and appears broken with an ERR_TOO_MANY_REQUESTS message.

Please note if I reload the page I will get the same error. If I open a new tab and access directly https://mydomain.tld/newsletter/subscriber/new/ I get the home page without any message which is a normal behavior. In webserver log there is not error related to this issue. Not even in PHP log.

**Comment by Schrank** [comment]
Thanks for your issue. Can you please attach a screenshot of the error "The page is not loading and appears broken with an ERR_TOO_MANY_REQUESTS message."

**Comment by ADDISON74** [comment]
In order to reproduce this issue please follow these steps:

1.  Load in frontend the Home page. Show the Inspector window in your browser and make visible the input box with class named mhhs-input. Fill up both input text boxes and subscribe.

![1](https://user-images.githubusercontent.com/8360474/100768306-68a32280-3403-11eb-82b6-5a02fbd6bcfa.jpg)

2. The extension identifies correctly this request as SPAM. Check the URL it is /newsletter/subscriber/new/. Fill up the newsletter input text box with an email address, without making visible this time the input text box with class named mhss-input and subscribe again.

![2](https://user-images.githubusercontent.com/8360474/100768419-8bcdd200-3403-11eb-82a3-ba8628b420a2.jpg)

3.  The page is not loading with error "This page in not working"  ... it redirected you too many times. Now check your webserver access log an you will see about 40 lines dedicated to /newsletter/subscriber/new/ path request.

![3](https://user-images.githubusercontent.com/8360474/100768707-dd765c80-3403-11eb-95a2-51744e78dbc1.jpg)

It could be a Magento issue ...

**Comment by Schrank** [comment]
Weird, the module should redirect to honeyspam/error

To make it short: I'm super happy to merge a pull request which fixes the problem - if it is inside the module (which I assume). But due to the fact, that the module doesn't do its job properly anymore, because the spambots are too specialized or smart I don't want to invest any time into this anymore.

**Comment by Schrank** [comment]
And the possibility that a human triggers this bug is nearly 0 :-)

**Comment by ADDISON74** [comment]
I will check why the module is redirecting to /newsletter/subscriber/new instead of /honeyspam/error as you said. 

Keep this issue open in case others will have time to check and fix the module related to this issue. I can change the title if you want to "Wrong redirection".

**Comment by ADDISON74** [comment]
@Schrank: the same issue related to URL's is happening for the other forms. Instead of getting /honeyspam/error I get:

(contact form) /contacts/index/post/
(create account) /customer/account/createpost/
(write review) /review/product/post/id/809/

It will be great if someone who contributed to the code will investigate this issue.
