### ISSUE TITLE
Question: Enable spam indexing?

### ISSUE THREAD

**Issue by ADDISON74** [magento-hackathon/HoneySpam#68]
May I ask you what this option is doing "Enable spam indexing for input fields"?

**Comment by sprankhub** [comment]
You can pretty much see what happens in [Hackathon_HoneySpam_Model_Checker](https://github.com/magento-hackathon/HoneySpam/blob/1cea728cd4411de4b78db1708399245caaac5c39/app/code/community/Hackathon/HoneySpam/Model/Checker.php). It checks for certain rules like:

* Some fields have idential values.
* Value contains numbers only.
* More than three consecutive vowels.
* ...
