### ISSUE TITLE
OpenMage integration allowed?

### ISSUE THREAD

**Issue by sreichel** [magento-hackathon/HoneySpam#76]
Is it okay to add this to OpenMage core?

**Comment by Schrank** [comment]
I'm fine with it, but imho it is useless today 😢  So from my point of view: Better don't because it gives a wrong impression of helping today

**Comment by Schrank** [comment]
@sreichel Due to the fact, that the license allows this, I'll close the ticket - if you have more questions or remarks, please comment!"
